steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/zinc-mantra-440520-a9/cancer-predection-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/zinc-mantra-440520-a9/cancer-predection-app']
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'cancer-predection-app'
      - '--image'
      - 'gcr.io/zinc-mantra-440520-a9/cancer-predection-app'
      - '--region'
      - 'europe-southwest1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
images:
  - 'gcr.io/zinc-mantra-440520-a9/cancer-predection-app'
